### ISSUE TITLE
Add buffer decoding to the `json` encoding

### ISSUE THREAD

**Issue by wesleytodd** [Level/codec#13]
When you use the `json` encoding and store a buffer you get back an object like `{type: 'Buffer': data: [...]}`.  It would be nice to augment the `JSON.parse` with buffer handling.  Is this something that you would all be interested in accepting a PR for?

**Comment by juliangruber** [comment]
you can also pass a custom encoding, like

```js
var codec = new Codec({
  keyEncoding: 'utf8',
  valueEncoding: { encode: encode, decode: decode }
})
```

I guess we should document this better. Would this approach work for you, together with a library like https://github.com/dominictarr/json-buffer

**Comment by wesleytodd** [comment]
I was using a custom encoding that just decoded the fields I knew were buffers.  This `json-buffer` module seems like the best solution.  I will put together a doc PR to levelup which adds this in the section about json encoding.  Thanks!
