### ISSUE TITLE
Clarification on buffer : boolean

### ISSUE THREAD

**Issue by MeirionHughes** [Level/codec#19]
I'm currently exploring the idea of making the codec typing a little more strict, but need some clarification. 

From what I can see; a codec encoder looks like this: 

```ts
  type CodecEncoder<I> = CodecStringEncoder<I> | CodecBufferEncoder<I>

  interface CodecStringEncoder<I> {
    encode: (val: I) => string;
    decode: (val: string) => I;
    buffer: false;
    type: string
  }

  interface CodecBufferEncoder<I> {
    encode: (val: I) => Buffer;
    decode: (val: Buffer) => I;
    buffer: true;
    type: string
  }
```
such that: 

* if `buffer === false` then it is expected that the encoder will 
  * encode _to_ a `string`
  * decode _from_ a `string`

* if `buffer === true` then it is expected that the encoder will 
  * encode _to_ a `Buffer`
  * decode _from_ a `Buffer`

Is this correct?

cc: @vweevers

**Comment by MeirionHughes** [comment]
On second thought, I think I'll keep it simple: 

```ts
  interface CodecEncoder<I> {
    encode: (val: I) => any;
    decode: (val: any) => I;
    buffer: boolean;
    type: string
  }
```

too much potential inconsistencies with possible down implementation + options. The only sure thing is that the codec should encode from and decode to some expected type.

**Comment by vweevers** [comment]
If you still need it, @juliangruber might be able to explain the semantics of `buffer`. We should document that anyhow (eventually).

**Comment by vweevers** [comment]
FWIW @MeirionHughes, the `buffer` property is now documented: https://github.com/level/codec#encoding-format.

And to add to that: the `buffer` semantics only apply to `decode()`, not  `encode()`. Though typically, if `encode()` yields a Buffer, then it makes sense that `decode()` *takes* a Buffer.
