### ISSUE TITLE
Question on coverage

### ISSUE THREAD

**Issue by ralphtheninja** [Level/codec#37]
So, given the current state we have the following results:

![screenshot from 2018-07-19 12-08-46](https://user-images.githubusercontent.com/308049/42936526-9c8af616-8b4c-11e8-8462-8f5da09ccf21.png)

I want to write a test that covers the following line https://github.com/Level/codec/blob/63d29a52d96bc4d431fb62ad5a5d08be8b0d42a5/index.js#L97

So I add the following test:

```js
  t.test('no keys and no values not decoding', function (t) {
    var decoder = codec.createStreamDecoder({})
    t.equal(decoder(null, Buffer.from('hey')), undefined)
    t.equal(decoder(Buffer.from('hey')), undefined)
    t.end()
  })
```

The test works (passes) and covers the line correctly. However, for some reason `nyc` reports new lines in the code that aren't covered, which seems a bit weird to me. How can adding an extra test _remove_ coverage? At worst it it's a bad test that doesn't _add_ coverage, but it should never remove coverage imo. See below:

![screenshot from 2018-07-19 12-15-23](https://user-images.githubusercontent.com/308049/42936818-79355bce-8b4d-11e8-9718-ad878983bd28.png)

What's going on here?

**Comment by vweevers** [comment]
Perhaps those lines are partially covered, and your test changes the balance of how many times certain code branches are hit.

`nyc report --reporter=html` could tell you more.

**Comment by ralphtheninja** [comment]
Also, there's seem to be a difference between red lines and yellow lines. Not sure what the color coding here means.

> nyc report --reporter=html could tell you more.

Cool, will check it out.
