### ISSUE TITLE
this broke legacy `encoding: name` alias for `valueEncoding: name`

### ISSUE THREAD

**Issue by dominictarr** [Level/codec#7]
there was lots of stuff that used that, so updating to latest level breaks all that stuff.

should be like this:
https://github.com/Level/levelup/blob/4c81da838f5b435b498e45b59025c3da463f8d10/lib/codec.js#L14-L18

but it's like this:

https://github.com/Level/codec/blob/master/index.js#L22-L26

**Comment by juliangruber** [comment]
yeah we removed that as part of levelup@1.0.0. I'm not against adding it back as long as there isn't too much code clutter

**Comment by jcrugzz** [comment]
Personally i think we should be less ambiguous since there is a `keyEncoding` and `valueEncoding`. It is a valid semver breaking change, it can just result in some unfortunate changes in dependent modules. @dominictarr how many modules did it break? Is it reasonable to simply find/replace `encoding` to `valueEncoding`?

**Comment by dominictarr** [comment]
That isn't completely reliable. I mean, it doesn't really make anything _work_ better it is just a naming nitpick.
A breaking change is just creates a lot of work for very little return.

**Comment by jcrugzz** [comment]
@dominictarr fair. I totally see the more work argument. My argument was whether that more work is worth better clarity of api options. I also understand that it is a rare option that would get tripped up on by a user but my OCD was running a bit sensitively this morning ;). I'm ok with this being implemented again.

**Comment by dominictarr** [comment]
sure, well what you do is remove the legacy version from the documentation but don't remove support for it. maybe add code comments to say `//LEGACY` in caps. The thing with the "work" is that a lot of that will be undone. I wrote a bunch of level modules that I havn't used in ages, so I have very little reason to update them. They are gonna stop working with the latest version... I'd just rather that if they where to stop working, it was for something that made a big difference to performance or simplicity, not just a little naming thing.

**Comment by ralphtheninja** [comment]
> should be like this:
> https://github.com/Level/levelup/blob/4c81da838f5b435b498e45b59025c3da463f8d10/lib/codec.js#L14-L18

That can certainly be written more clearly.

@juliangruber If we put it back, would that mean a new major of levelup?

**Comment by ralphtheninja** [comment]
I would really like to go to the bottom with this, `level-sublevel` is an important module.

**Comment by ralphtheninja** [comment]
@dominictarr What's the breaking part? Afaict it differers only on the last statement, it used to default to `utf-8` if _nothing_ else is set, which today defaults to https://github.com/Level/codec/blob/master/index.js#L26

**Comment by dominictarr** [comment]
@ralphtheninja it's fixed now because they merged my pull request, which means this can now be closed.
it was like this, previously: https://github.com/Level/codec/blob/0725e77d8300090e907dae0d84974cc3776bd860/index.js#L22-L26

**Comment by ralphtheninja** [comment]
> @ralphtheninja it's fixed now because they merged my pull request, which means this can now be closed.
> it was like this, previously: https://github.com/Level/codec/blob/0725e77d8300090e907dae0d84974cc3776bd860/index.js#L22-L26

Aaah nice!

**Comment by dominictarr** [comment]
@ralphtheninja it's fixed now because they merged my pull request, which means this can now be closed.
it was like this, previously: https://github.com/Level/codec/blob/0725e77d8300090e907dae0d84974cc3776bd860/index.js#L22-L26
